/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Config */
        patch: operations["patch_config_api_config_patch"];
        trace?: never;
    };
    "/api/config/secrets/discogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Discogs */
        put: operations["set_discogs_api_config_secrets_discogs_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/secrets/deepseek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Deepseek */
        put: operations["set_deepseek_api_config_secrets_deepseek_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tracks */
        get: operations["list_tracks_api_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Track */
        get: operations["get_track_api_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Track */
        patch: operations["patch_track_api_tracks__track_id__patch"];
        trace?: never;
    };
    "/api/tracks/{track_id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Location */
        get: operations["track_location_api_tracks__track_id__location_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Audio */
        get: operations["track_audio_api_tracks__track_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/artwork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Artwork */
        get: operations["track_artwork_api_tracks__track_id__artwork_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Waveform */
        get: operations["track_waveform_api_tracks__track_id__waveform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/cancel-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel All Jobs */
        post: operations["cancel_all_jobs_api_jobs_cancel_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/archive-completed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Completed Jobs */
        post: operations["archive_completed_jobs_api_jobs_archive_completed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Job History */
        delete: operations["delete_job_history_api_jobs_history_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Job */
        post: operations["archive_job_api_jobs__job_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/dig": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dig */
        post: operations["dig_api_discovery_dig_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/rematch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rematch Discovery */
        post: operations["rematch_discovery_api_discovery_rematch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Discovery Interaction */
        post: operations["record_discovery_interaction_api_discovery_interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mpc/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mpc Jobs */
        get: operations["list_mpc_jobs_api_mpc_jobs_get"];
        put?: never;
        /** Create Mpc Job */
        post: operations["create_mpc_job_api_mpc_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mpc/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Mpc Job */
        delete: operations["cancel_mpc_job_api_mpc_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mpc/jobs/clear-finished": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Finished Mpc Jobs */
        post: operations["clear_finished_mpc_jobs_api_mpc_jobs_clear_finished_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/previews/prefetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Status */
        get: operations["preview_status_api_previews_prefetch_get"];
        put?: never;
        /** Prefetch Previews */
        post: operations["prefetch_previews_api_previews_prefetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/previews/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Preview */
        post: operations["create_preview_api_previews__video_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/previews/{video_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Audio */
        get: operations["preview_audio_api_previews__video_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Crates */
        get: operations["list_crates_api_crates_get"];
        put?: never;
        /** Create Crate */
        post: operations["create_crate_api_crates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crates/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crate Overview */
        get: operations["crate_overview_api_crates_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crates/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crate Suggestions */
        get: operations["crate_suggestions_api_crates_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crates/{crate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crate */
        get: operations["get_crate_api_crates__crate_id__get"];
        put?: never;
        post?: never;
        /** Delete Crate */
        delete: operations["delete_crate_api_crates__crate_id__delete"];
        options?: never;
        head?: never;
        /** Patch Crate */
        patch: operations["patch_crate_api_crates__crate_id__patch"];
        trace?: never;
    };
    "/api/crates/{crate_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign Crate Tracks */
        put: operations["assign_crate_tracks_api_crates__crate_id__tracks_put"];
        /** Add Crate Tracks Compat */
        post: operations["add_crate_tracks_compat_api_crates__crate_id__tracks_post"];
        /** Remove Crate Tracks */
        delete: operations["remove_crate_tracks_api_crates__crate_id__tracks_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigPatch */
        ConfigPatch: {
            /**
             * Section
             * @enum {string}
             */
            section: "general" | "downloader" | "stems" | "discovery" | "export" | "ui";
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Has Discogs Token */
            has_discogs_token: boolean;
            /** Has Deepseek Key */
            has_deepseek_key: boolean;
            /** Keyring Available */
            keyring_available: boolean;
            /** Engine Ready */
            engine_ready: boolean;
            /** Engine Error */
            engine_error?: string | null;
        };
        /** Crate */
        Crate: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Color
             * @default #F4DF00
             */
            color: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Track Count
             * @default 0
             */
            track_count: number;
        };
        /** CrateAssignmentRequest */
        CrateAssignmentRequest: {
            /** Track Ids */
            track_ids: number[];
            /**
             * Allow Moves
             * @default false
             */
            allow_moves: boolean;
        };
        /** CrateAssignmentResult */
        CrateAssignmentResult: {
            /**
             * Assigned
             * @default 0
             */
            assigned: number;
            /**
             * Moved
             * @default 0
             */
            moved: number;
            /**
             * Unchanged
             * @default 0
             */
            unchanged: number;
        };
        /** CrateCreate */
        CrateCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Color
             * @default #F4DF00
             */
            color: string;
        };
        /** CrateDetail */
        CrateDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Color
             * @default #F4DF00
             */
            color: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Track Count
             * @default 0
             */
            track_count: number;
            tracks: components["schemas"]["TrackPage"];
        };
        /** CrateOverview */
        CrateOverview: {
            /** Items */
            items: components["schemas"]["Crate"][];
            /** Unassigned Count */
            unassigned_count: number;
        };
        /** CratePatch */
        CratePatch: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Color */
            color: string;
        };
        /** CrateRef */
        CrateRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** CrateSuggestion */
        CrateSuggestion: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "month" | "genre" | "mood";
            /** Label */
            label: string;
            /** Proposed Name */
            proposed_name: string;
            /** Track Ids */
            track_ids: number[];
            /** Count */
            count: number;
        };
        /** CrateTrackRemoval */
        CrateTrackRemoval: {
            /** Track Ids */
            track_ids: number[];
        };
        /** DiscoveryFilters */
        DiscoveryFilters: {
            /** Year Min */
            year_min?: number | null;
            /** Year Max */
            year_max?: number | null;
            /** Country */
            country?: string | null;
            /** Genre */
            genre?: string | null;
            /** Style */
            style?: string | null;
            /** Query */
            query?: string | null;
            /**
             * Min Have
             * @default 10
             */
            min_have: number;
            /**
             * Max Have
             * @default 3000
             */
            max_have: number;
            /**
             * Prioritize Samples
             * @default true
             */
            prioritize_samples: boolean;
            /**
             * Sample Intensity
             * @default 0.9
             */
            sample_intensity: number;
            /**
             * Allow Compilations
             * @default false
             */
            allow_compilations: boolean;
            /**
             * Profile
             * @default boom_bap
             * @enum {string}
             */
            profile: "boom_bap" | "lofi" | "global" | "cinematic";
            /**
             * Count
             * @default 8
             */
            count: number;
        };
        /** DiscoveryInteractionRequest */
        DiscoveryInteractionRequest: {
            suggestion: components["schemas"]["Suggestion"];
            /**
             * Action
             * @enum {string}
             */
            action: "preview" | "queue" | "mpc";
        };
        /** DiscoveryRematchRequest */
        DiscoveryRematchRequest: {
            suggestion: components["schemas"]["Suggestion"];
            /** Exclude Video Ids */
            exclude_video_ids?: string[];
        };
        /** DiscoveryResponse */
        DiscoveryResponse: {
            /** Items */
            items: components["schemas"]["Suggestion"][];
            /**
             * Demo
             * @default false
             */
            demo: boolean;
            /** Message */
            message?: string | null;
        };
        /** ExportRequest */
        ExportRequest: {
            /** Track Ids */
            track_ids: number[];
            /** Destination */
            destination: string;
            /**
             * Chop Kit
             * @default false
             */
            chop_kit: boolean;
        };
        /** ExportResponse */
        ExportResponse: {
            /** Accepted */
            accepted: number;
            /** Destination */
            destination: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Engine Ready */
            engine_ready: boolean;
            /** Engine Error */
            engine_error?: string | null;
        };
        /** MpcExportRequest */
        MpcExportRequest: {
            suggestion: components["schemas"]["Suggestion"];
            /**
             * Mode
             * @default both
             * @enum {string}
             */
            mode: "song" | "stems" | "both";
        };
        /** MpcJob */
        MpcJob: {
            /** Job Id */
            job_id: string;
            /** Video Id */
            video_id: string;
            /** Display Name */
            display_name: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "song" | "stems" | "both";
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "completed" | "failed" | "cancelled";
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Percent
             * @default 0
             */
            percent: number;
            /** Error Message */
            error_message?: string | null;
            /** Track Dir */
            track_dir?: string | null;
        };
        /** PreviewPrefetchItem */
        PreviewPrefetchItem: {
            /** Video Id */
            video_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "downloading" | "decoding" | "ready" | "failed" | "cancelled";
            /**
             * Percent
             * @default 0
             */
            percent: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Error Message */
            error_message?: string | null;
        };
        /** PreviewPrefetchRequest */
        PreviewPrefetchRequest: {
            /** Video Ids */
            video_ids: string[];
        };
        /** PreviewPrefetchResponse */
        PreviewPrefetchResponse: {
            /** Items */
            items: components["schemas"]["PreviewPrefetchItem"][];
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Video Id */
            video_id: string;
            /** Audio Url */
            audio_url: string;
            /** Peaks */
            peaks: number[];
            /** Duration Seconds */
            duration_seconds: number;
            /** Partial */
            partial: boolean;
        };
        /** QueueActionResponse */
        QueueActionResponse: {
            /** Affected */
            affected: number;
        };
        /** QueueJob */
        QueueJob: {
            /** Id */
            id: number;
            /** Source Url */
            source_url: string;
            /** Display Name */
            display_name?: string | null;
            /** Status */
            status: string;
            /**
             * Operation
             * @default ingest
             * @enum {string}
             */
            operation: "ingest" | "stems";
            /**
             * Origin
             * @default manual_rip
             */
            origin: string;
            /** Progress Pct */
            progress_pct: number;
            /**
             * Stage Percent
             * @default 0
             */
            stage_percent: number;
            /** Current Stage */
            current_stage?: string | null;
            /** Status Message */
            status_message?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Failure Stage */
            failure_stage?: string | null;
            /** Track Id */
            track_id?: number | null;
            /** Enable Stems */
            enable_stems: boolean;
            /** Retry Of Job Id */
            retry_of_job_id?: number | null;
            /** Archived At */
            archived_at?: string | null;
            /** Queue Position */
            queue_position?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** QueuePage */
        QueuePage: {
            /** Items */
            items: components["schemas"]["QueueJob"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            summary: components["schemas"]["QueueSummary"];
        };
        /** QueueRequest */
        QueueRequest: {
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Origin
             * @default manual_rip
             * @enum {string}
             */
            origin: "manual_rip" | "digital_crate" | "retry";
            /**
             * Output Format
             * @default m4a
             * @enum {string}
             */
            output_format: "m4a" | "mp3" | "wav";
            /**
             * Enable Stems
             * @default false
             */
            enable_stems: boolean;
            /**
             * Use Ai Metadata
             * @default true
             */
            use_ai_metadata: boolean;
            /** Hint Genre */
            hint_genre?: string | null;
            /** Hint Country */
            hint_country?: string | null;
            /** Hint Year */
            hint_year?: number | null;
            /** Hint Discogs Master Id */
            hint_discogs_master_id?: number | null;
            /** Hint Discogs Release Id */
            hint_discogs_release_id?: number | null;
            /** Source Platform Override */
            source_platform_override?: string | null;
        };
        /** QueueSummary */
        QueueSummary: {
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Waiting
             * @default 0
             */
            waiting: number;
            /**
             * Completed
             * @default 0
             */
            completed: number;
            /**
             * Attention
             * @default 0
             */
            attention: number;
            /** Current Job Id */
            current_job_id?: number | null;
        };
        /** SecretPatch */
        SecretPatch: {
            /** Value */
            value?: string | null;
        };
        /** Suggestion */
        Suggestion: {
            /** Discogs Master Id */
            discogs_master_id: number;
            /** Discogs Release Id */
            discogs_release_id?: number | null;
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Year */
            year?: number | null;
            /** Country */
            country?: string | null;
            /** Genre */
            genre?: string | null;
            /** Style */
            style?: string | null;
            /** Youtube Url */
            youtube_url?: string | null;
            /** Youtube Video Id */
            youtube_video_id?: string | null;
            /** Youtube Title */
            youtube_title?: string | null;
            /** Youtube Duration Seconds */
            youtube_duration_seconds?: number | null;
            /** Match Score */
            match_score?: number | null;
            /**
             * Sample Score
             * @default 1
             */
            sample_score: number;
            /** Sample Reasons */
            sample_reasons?: string[];
            /** Artwork Url */
            artwork_url?: string | null;
            /** Discogs Url */
            discogs_url?: string | null;
            /**
             * Sample Friendly
             * @default true
             */
            sample_friendly: boolean;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /** Track */
        Track: {
            /** Id */
            id: number;
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Album */
            album?: string | null;
            /** Genre */
            genre?: string | null;
            /** Style */
            style?: string | null;
            /** Country */
            country?: string | null;
            /** Year */
            year?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Bpm */
            bpm?: number | null;
            /** Musical Key */
            musical_key?: string | null;
            /** Camelot Key */
            camelot_key?: string | null;
            /**
             * Stems Separated
             * @default false
             */
            stems_separated: boolean;
            /** Source Url */
            source_url: string;
            /** Source Platform */
            source_platform: string;
            /** Date Added */
            date_added?: string | null;
            /** Rating */
            rating?: number | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * File Available
             * @default false
             */
            file_available: boolean;
            /** Artwork Url */
            artwork_url?: string | null;
            /**
             * Output Format
             * @default m4a
             * @enum {string}
             */
            output_format: "m4a" | "mp3" | "wav";
            crate?: components["schemas"]["CrateRef"] | null;
        };
        /** TrackLocation */
        TrackLocation: {
            /** File Path */
            file_path: string;
            /** Available */
            available: boolean;
        };
        /** TrackPage */
        TrackPage: {
            /** Items */
            items: components["schemas"]["Track"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** TrackPatch */
        TrackPatch: {
            /** Rating */
            rating?: number | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_config_api_config_patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_discogs_api_config_secrets_discogs_put: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_deepseek_api_config_secrets_deepseek_put: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tracks_api_tracks_get: {
        parameters: {
            query?: {
                query?: string | null;
                genre?: string | null;
                decade?: number | null;
                min_bpm?: number | null;
                max_bpm?: number | null;
                camelot_key?: string | null;
                has_stems?: boolean | null;
                min_rating?: number | null;
                tag?: string | null;
                crate_id?: number | null;
                unassigned?: boolean | null;
                limit?: number;
                offset?: number;
                order_by?: string;
                order_desc?: boolean;
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_api_tracks__track_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_track_api_tracks__track_id__patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_location_api_tracks__track_id__location_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackLocation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_audio_api_tracks__track_id__audio_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_artwork_api_tracks__track_id__artwork_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_waveform_api_tracks__track_id__waveform_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                view?: string;
                status?: string | null;
                query?: string;
                limit?: number;
                offset?: number;
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_all_jobs_api_jobs_cancel_all_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_completed_jobs_api_jobs_archive_completed_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_history_api_jobs_history_delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_jobs__job_id__retry_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_job_api_jobs__job_id__archive_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dig_api_discovery_dig_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryFilters"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rematch_discovery_api_discovery_rematch_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryRematchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_discovery_interaction_api_discovery_interactions_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryInteractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mpc_jobs_api_mpc_jobs_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MpcJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mpc_job_api_mpc_jobs_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MpcExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MpcJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_mpc_job_api_mpc_jobs__job_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_finished_mpc_jobs_api_mpc_jobs_clear_finished_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_status_api_previews_prefetch_get: {
        parameters: {
            query: {
                video_ids: string;
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewPrefetchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prefetch_previews_api_previews_prefetch_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewPrefetchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewPrefetchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_preview_api_previews__video_id__post: {
        parameters: {
            query?: {
                mode?: string;
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_audio_api_previews__video_id__audio_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crates_api_crates_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Crate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crate_api_crates_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Crate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crate_overview_api_crates_overview_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrateOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crate_suggestions_api_crates_suggestions_get: {
        parameters: {
            query?: {
                include_assigned?: boolean;
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrateSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crate_api_crates__crate_id__get: {
        parameters: {
            query?: {
                query?: string | null;
                limit?: number;
                offset?: number;
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                crate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrateDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_crate_api_crates__crate_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                crate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_crate_api_crates__crate_id__patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                crate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CratePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Crate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_crate_tracks_api_crates__crate_id__tracks_put: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                crate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrateAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrateAssignmentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_crate_tracks_compat_api_crates__crate_id__tracks_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                crate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrateAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrateAssignmentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_crate_tracks_api_crates__crate_id__tracks_delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                crate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrateTrackRemoval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_exports_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
