/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Config */
        patch: operations["patch_config_api_config_patch"];
        trace?: never;
    };
    "/api/config/secrets/discogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Discogs */
        put: operations["set_discogs_api_config_secrets_discogs_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/secrets/deepseek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Deepseek */
        put: operations["set_deepseek_api_config_secrets_deepseek_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tracks */
        get: operations["list_tracks_api_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Track */
        get: operations["get_track_api_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Track */
        patch: operations["patch_track_api_tracks__track_id__patch"];
        trace?: never;
    };
    "/api/tracks/{track_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Audio */
        get: operations["track_audio_api_tracks__track_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Waveform */
        get: operations["track_waveform_api_tracks__track_id__waveform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/dig": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dig */
        post: operations["dig_api_discovery_dig_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/previews/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Preview */
        post: operations["create_preview_api_previews__video_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/previews/{video_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Audio */
        get: operations["preview_audio_api_previews__video_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Crates */
        get: operations["list_crates_api_crates_get"];
        put?: never;
        /** Create Crate */
        post: operations["create_crate_api_crates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crates/{crate_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Crate Tracks */
        post: operations["add_crate_tracks_api_crates__crate_id__tracks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crates/{crate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Crate */
        delete: operations["delete_crate_api_crates__crate_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigPatch */
        ConfigPatch: {
            /**
             * Section
             * @enum {string}
             */
            section: "general" | "downloader" | "stems" | "discovery" | "export" | "ui";
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Has Discogs Token */
            has_discogs_token: boolean;
            /** Has Deepseek Key */
            has_deepseek_key: boolean;
            /** Keyring Available */
            keyring_available: boolean;
            /** Engine Ready */
            engine_ready: boolean;
            /** Engine Error */
            engine_error?: string | null;
        };
        /** Crate */
        Crate: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Track Count
             * @default 0
             */
            track_count: number;
        };
        /** CrateCreate */
        CrateCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** CrateTracks */
        CrateTracks: {
            /** Track Ids */
            track_ids: number[];
        };
        /** DiscoveryFilters */
        DiscoveryFilters: {
            /** Year Min */
            year_min?: number | null;
            /** Year Max */
            year_max?: number | null;
            /** Country */
            country?: string | null;
            /** Genre */
            genre?: string | null;
            /** Style */
            style?: string | null;
            /** Query */
            query?: string | null;
            /**
             * Min Have
             * @default 10
             */
            min_have: number;
            /**
             * Max Have
             * @default 3000
             */
            max_have: number;
            /**
             * Prioritize Samples
             * @default true
             */
            prioritize_samples: boolean;
            /**
             * Sample Intensity
             * @default 0.6
             */
            sample_intensity: number;
            /**
             * Allow Compilations
             * @default false
             */
            allow_compilations: boolean;
            /**
             * Count
             * @default 8
             */
            count: number;
        };
        /** DiscoveryResponse */
        DiscoveryResponse: {
            /** Items */
            items: components["schemas"]["Suggestion"][];
            /**
             * Demo
             * @default false
             */
            demo: boolean;
            /** Message */
            message?: string | null;
        };
        /** ExportRequest */
        ExportRequest: {
            /** Track Ids */
            track_ids: number[];
            /** Destination */
            destination: string;
            /**
             * Chop Kit
             * @default false
             */
            chop_kit: boolean;
        };
        /** ExportResponse */
        ExportResponse: {
            /** Accepted */
            accepted: number;
            /** Destination */
            destination: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Engine Ready */
            engine_ready: boolean;
            /** Engine Error */
            engine_error?: string | null;
        };
        /** PreviewResponse */
        PreviewResponse: {
            /** Video Id */
            video_id: string;
            /** Audio Url */
            audio_url: string;
            /** Peaks */
            peaks: number[];
            /** Duration Seconds */
            duration_seconds: number;
            /** Partial */
            partial: boolean;
        };
        /** QueueJob */
        QueueJob: {
            /** Id */
            id: number;
            /** Source Url */
            source_url: string;
            /** Display Name */
            display_name?: string | null;
            /** Status */
            status: string;
            /** Progress Pct */
            progress_pct: number;
            /** Current Stage */
            current_stage?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Track Id */
            track_id?: number | null;
            /** Enable Stems */
            enable_stems: boolean;
            /** Created At */
            created_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** QueueRequest */
        QueueRequest: {
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /**
             * Enable Stems
             * @default false
             */
            enable_stems: boolean;
            /**
             * Use Ai Metadata
             * @default true
             */
            use_ai_metadata: boolean;
            /** Hint Genre */
            hint_genre?: string | null;
            /** Hint Country */
            hint_country?: string | null;
            /** Hint Year */
            hint_year?: number | null;
            /** Hint Discogs Master Id */
            hint_discogs_master_id?: number | null;
            /** Hint Discogs Release Id */
            hint_discogs_release_id?: number | null;
            /** Source Platform Override */
            source_platform_override?: string | null;
        };
        /** SecretPatch */
        SecretPatch: {
            /** Value */
            value?: string | null;
        };
        /** Suggestion */
        Suggestion: {
            /** Discogs Master Id */
            discogs_master_id: number;
            /** Discogs Release Id */
            discogs_release_id?: number | null;
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Year */
            year?: number | null;
            /** Country */
            country?: string | null;
            /** Genre */
            genre?: string | null;
            /** Style */
            style?: string | null;
            /** Youtube Url */
            youtube_url?: string | null;
            /** Youtube Video Id */
            youtube_video_id?: string | null;
            /** Youtube Title */
            youtube_title?: string | null;
            /** Youtube Duration Seconds */
            youtube_duration_seconds?: number | null;
            /** Match Score */
            match_score?: number | null;
            /**
             * Sample Friendly
             * @default true
             */
            sample_friendly: boolean;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /** Track */
        Track: {
            /** Id */
            id: number;
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Album */
            album?: string | null;
            /** Genre */
            genre?: string | null;
            /** Style */
            style?: string | null;
            /** Country */
            country?: string | null;
            /** Year */
            year?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Bpm */
            bpm?: number | null;
            /** Musical Key */
            musical_key?: string | null;
            /** Camelot Key */
            camelot_key?: string | null;
            /**
             * Stems Separated
             * @default false
             */
            stems_separated: boolean;
            /** Source Url */
            source_url: string;
            /** Source Platform */
            source_platform: string;
            /** Date Added */
            date_added?: string | null;
            /** Rating */
            rating?: number | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * File Available
             * @default false
             */
            file_available: boolean;
        };
        /** TrackPage */
        TrackPage: {
            /** Items */
            items: components["schemas"]["Track"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** TrackPatch */
        TrackPatch: {
            /** Rating */
            rating?: number | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_config_api_config_patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_discogs_api_config_secrets_discogs_put: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_deepseek_api_config_secrets_deepseek_put: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tracks_api_tracks_get: {
        parameters: {
            query?: {
                query?: string | null;
                genre?: string | null;
                decade?: number | null;
                min_bpm?: number | null;
                max_bpm?: number | null;
                camelot_key?: string | null;
                has_stems?: boolean | null;
                min_rating?: number | null;
                tag?: string | null;
                crate_id?: number | null;
                limit?: number;
                offset?: number;
                order_by?: string;
                order_desc?: boolean;
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_api_tracks__track_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_track_api_tracks__track_id__patch: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_audio_api_tracks__track_id__audio_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_waveform_api_tracks__track_id__waveform_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dig_api_discovery_dig_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryFilters"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_preview_api_previews__video_id__post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_audio_api_previews__video_id__audio_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crates_api_crates_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Crate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crate_api_crates_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Crate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_crate_tracks_api_crates__crate_id__tracks_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                crate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrateTracks"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_crate_api_crates__crate_id__delete: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path: {
                crate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_exports_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-crate-token"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
